refactor metod validate and fix tests
Isupovd/tester-elective pull request #1
Opened 2017-04-25 10:48 UTC by Isupovd

2017-04-25 11:51 UTC, pastuhov commented on tests/models/ContactFormTest.php
> +        $this->assertFalse($object->validate());
слабенький негативный сценарий, лучше поле присвоить, хотя бы одно

2017-04-26 09:46 UTC, pastuhov requested changes

2017-04-26 09:46 UTC, pastuhov commented on tests/models/ContactFormTest.php
> +        $object->save($object);
а как ты проверил что save() отработал? что все ок в файле?

2017-04-26 12:23 UTC, Isupovd commented on tests/models/ContactFormTest.php
> +        $this->assertFalse($object->validate());
fix

2017-04-26 16:28 UTC, pastuhov commented on tests/models/ContactFormTest.php
> +    public function testSave()
на сохранение достаточно двух медодов, проверить успешное сохранение и проверить неуспешное
в проверке надо проверять не только то, что метод вернул успех\неуспех, но и проверить сам файл с образцом

2017-04-28 12:53 UTC, pastuhov requested changes

2017-04-28 12:53 UTC, pastuhov commented on tests/models/ContactFormTest.php
> +    public function testInvalidSave()
Тут файл тоже надо проверить

2017-04-28 12:53 UTC, pastuhov commented on tests/models/ContactFormTest.php
> +    public function testSave()
лучше два раза save и два раза проверить что там

2017-05-02 10:51 UTC, Isupovd commented on tests/models/ContactFormTest.php
> +    public function testInvalidSave()
fix

2017-05-02 10:53 UTC, Isupovd commented on tests/models/ContactFormTest.php
> +    public function testSave()
добавил двойную проверку файла

2017-05-02 10:55 UTC, pastuhov approved these changes

2017-05-02 10:56 UTC, merged